### ISSUE TITLE
Create a webhook level

### ISSUE THREAD

**Issue by arielleleon** [AllenNeuralDynamics/aind-watchdog-service#14]
Webhook alerts should have levels for users to opt into and should be configured in the watchdog rig config. A user should be able to receive info + errors or errors only or info only

**Comment by alexpiet** [comment]
Bumping this for visibility. 

The dynamic foraging task has 30+ sessions a day, so alerts for all successful uploads are overwhelming. It would be very valuable to get alerts for errors only. Especially if those alerts contained some information about the failure.
