### ISSUE TITLE
Add full example in README 

### ISSUE THREAD

**Issue by arielleleon** [AllenNeuralDynamics/aind-watchdog-service#17]
README should include full deploy example + start up. Need to include system checks and how to troubleshoot failures

**Comment by hanhou** [comment]
Yes, please add a full example!

**Comment by arielleleon** [comment]
@hanhou Can you check the README on the development branch and let me know if the instructions are documented good enough?

**Comment by hanhou** [comment]
It looks great. Thanks! I just left a comment in the PR.
