### ISSUE TITLE
remove models from repo and add to aind-data-transfer-models

### ISSUE THREAD

**Issue by arielleleon** [AllenNeuralDynamics/aind-watchdog-service#18]
aind-data-transfer-models should contain configurations for aind-watchdog-service.

**Comment by bruno-f-cruz** [comment]
I'm not sure I completely follow this decision. There should be a separation of concerns between the two packages. If one needs to update the watchdog models, only the watchdog package should be bumped not the `aind-data-transfer-models` one I reckon?

Is there a dependency that I am not appreciating perhaps?

**Comment by arielleleon** [comment]
That's actually a fair point. My rational was to have all transfer related models in the same location for easy import so that someone building the model wouldn't need to import aind-watchdog-service. Let me think about it...

**Comment by arielleleon** [comment]
Closing because I agree here with @bruno-f-cruz
