### ISSUE TITLE
Python version should be >=3.10 in pyproject.toml

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/aind-watchdog-service#25]
This following line requires python>=3.10. 

https://github.com/AllenNeuralDynamics/aind-watchdog-service/blob/a16286a151f0ae702c35ced630134bf58272a702/src/aind_watchdog_service/run_job.py#L38

**Comment by arielleleon** [comment]
@hanhou This has been taken care of in the development branch
