### ISSUE TITLE
Duplicate jobs submitted in a short period of time

### ISSUE THREAD

**Issue by hanhou** [AllenNeuralDynamics/aind-watchdog-service#27]
**Describe the bug**
The watchdog submits two or three jobs at once when there is only one change in the yml file.

**To Reproduce**
1. Start the watchdog by "Run Without Debugging" the `main.py` on `develop` branch. 
2. Copy and paste a yml file to `flag_dir`, or if it already exists, make a change to it and save.
3. The watchdog detects the change and submits two or three jobs at once.

**Expected behavior**
Only submit one job per (change of) yml file.

**Screenshots**
Example log file
[aind-watchdog-service.log](https://github.com/user-attachments/files/16037150/aind-watchdog-service.log)

An example case where 3 jobs are submitted within ~300 ms:
![image](https://github.com/AllenNeuralDynamics/aind-watchdog-service/assets/24734299/356b3aec-916a-4ca9-b151-b9e122a035db)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by arielleleon** [comment]
@hanhou I know what is going on here and I commented on it in [this ticket ](https://github.com/AllenNeuralDynamics/aind-physio-arch/issues/51)

**Comment by hanhou** [comment]
Makes sense! That's interesting. I think this could be of low priority since we don't use text editor in production.

**Comment by arielleleon** [comment]
@hanhou This has been fixed in the latest development release. I will coordinate with Alex to test and once we think this is good, I will have you close this issue
