### ISSUE TITLE
Fiber data assets are not being picked up by watchdog

### ISSUE THREAD

**Issue by jeromelecoq** [AllenNeuralDynamics/aind-watchdog-service#81]
**Describe the bug**
FIber datasets are currently not being uploaded through the watchdog. 
Checking the log here : /allen/programs/mindscope/workgroups/behavioral-dynamics/aind_logs/watchdog_logs/
It seems like no data picked up since 2024-10-07 
Some data were collected on 2024-10-10 but was not picked up. 

.yml are also created on the rig but not detected. 

Details reports is attached below 

**To Reproduce**
Check log on folder associated with fiber data. have yml file in transfer folder. 

**Expected behavior**
yml file should be read and processed. 
It is possible the background window process is down. 

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Details report: 
[2024-10-11-detailed-fiber-report.xlsx](https://github.com/user-attachments/files/17347547/2024-10-11-detailed-fiber-report.xlsx)
 here.

**Comment by jeromelecoq** [comment]
Note on excel sheet. from Alex:  "scheduled = on the schedule, but doesnt have a yml file. almost certainly because the mouse hasn't been run today (this email is created at 7am and 8pm)"

**Comment by alexpiet** [comment]
Resolved by restarting the watchdog service every day
